### PR TITLE
[HCP Vault Secrets] fix app & secret name validation

### LINKED ISSUE #728: Misleading validation error messages/validation doesn't match HCP web interface
### Terraform Version and Provider Version

```
Terraform version: v1.7.0
HCP provider version: 0.80
```

### Affected Resource(s)

* hcp_vault_secrets_app
* hcp_vault_secrets_secret
* (probably others as well)

### Description

As already discussed earlier on a call with @averche, the current validation error messages seem insufficient, there is no mention of a minimum/maximum length for the resource name:

- [resource_vault_secrets_app.go#L40C1-L48C6](https://github.com/hashicorp/terraform-provider-hcp/blob/main/internal/provider/vaultsecrets/resource_vault_secrets_app.go#L40C1-L48C6)
- [resource_vault_secrets_secret.go#L49-L68](https://github.com/hashicorp/terraform-provider-hcp/blob/main/internal/provider/vaultsecrets/resource_vault_secrets_secret.go#L49-L68)

Also, it seems that the HCP web interface allows to create secrets names with up to 64 characters.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by averche**
### :hammer_and_wrench: Description

Fixing the validation rules for HCP Vault Secrets app and secret names to match what we have on the server.

Fixes #728

### :building_construction: Acceptance tests

- [ ] Are there any feature flags that are required to use this functionality?
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

### CODE REVIEW

**Review by rodrigo-hcp — APPROVED** [review]

**Review by manish-hashicorp — APPROVED** [review]

File: internal/provider/vaultsecrets/resource_vault_secrets_secret.go [hunk 1]
```diff
@@ -50,19 +50,23 @@ func (r *resourceVaultsecretsSecret) Schema(_ context.Context, _ resource.Schema
 				Description: "The name of the application the secret can be found in",
 				Required:    true,
 				Validators: []validator.String{
+					stringvalidator.LengthAtLeast(3),
```
Comment (VinnyHC) [inline internal/provider/vaultsecrets/resource_vault_secrets_secret.go:53]: Apps use this common "hcp user settable slug":
https://github.com/hashicorp/cloud-vault-secrets/blob/main/internal/service/validation/service.go#L37

Wonder if it make sense to adopt this:
https://github.com/hashicorp/terraform-provider-hcp/blob/main/internal/providersdkv2/validators.go#L138

**Review by VinnyHC — APPROVED** [review]

File: internal/provider/vaultsecrets/resource_vault_secrets_secret.go (hunk 1 above)
Comment (averche) [reply internal/provider/vaultsecrets/resource_vault_secrets_secret.go:53]: Great find, did not know it exists! Thanks @VinnyHC

File: internal/provider/vaultsecrets/resource_vault_secrets_secret.go [hunk 2]
```diff
@@ -50,19 +50,23 @@ func (r *resourceVaultsecretsSecret) Schema(_ context.Context, _ resource.Schema
...
+					stringvalidator.LengthAtMost(36),
 					stringvalidator.RegexMatches(
-						regexp.MustCompile(`^[-\da-zA-Z]{3,36}$`),
-						"must contain only letters, numbers or hyphens",
+						regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9\-]+[a-zA-Z0-9]$`),
+						"must contain only ASCII letters, numbers, and hyphens; must not start or end with a hyphen",
```
Comment (fhemberger) [inline internal/provider/vaultsecrets/resource_vault_secrets_secret.go:57]: @averche Error message should contain min/max length as well.
