### PR TITLE
HPR-1208: Fix panic when `hcp_packer_image` points to an empty channel

### LINKED ISSUE #496: Terraform Provider Plugin Crashed
### Terraform Version and Provider Version

```
Terraform version: 1.4.4
HCP provider version: 0.56.0
```

### Affected Resource(s)

* hcp_XXXXX

### Terraform Configuration Files

```hcl
# create ec2 instance
data "hcp_packer_iteration" "ubuntu-apache" {
  bucket_name = "ubuntu-apache-aws"
  channel = "latest"
}
data "hcp_packer_image" "ubuntu-apache-aws" {
  bucket_name     = "ubuntu-apache-aws"
  channel         = "latest"
  cloud_provider  = "aws"
  region          = "eu-west-3"
}
resource "random_integer" "num" {
  min = 0
  max = local.subnet_count - 1
}

resource "aws_instance" "web_host" {
  ami                    = data.hcp_packer_image.ubuntu-apache-aws.cloud_image_id
  instance_type          = var.instance_type
  vpc_security_group_ids = [aws_security_group.web-node.id]
  subnet_id              = aws_subnet.web_subnet[local.az_num].id

  tags = {
    
      Name        = "${local.resource_prefix}-ec2"
      Environment = var.environment
      ttl = "24h"
      owner = var.owner
      region = var.region
      purpose = "test something fashion"
      atemi = var.atemi
    }
  
  monitoring = true
  ebs_optimized = true
  root_block_device {
    encrypted = true
  }

  lifecycle {
      postcondition {
        condition = self.instance_type == "t3.large"
        error_message = "The selected instance type is to big for this usage"
      }

      postcondition {
        condition = self.tags["purpose"] == "test something fashion"
        error_message = "The selected instance type is to big for this usage"
      }
      postcondition {
        condition = self.ami == data.hcp_packer_image.ubuntu-apache-aws.cloud_image_id
        error_message = "you don't use the latest available image data.hcp_packer_image.worker.cloud_image_id"
      }
    }
}
```

### Debug Output

Error: Plugin did not respond
with data.hcp_packer_iteration.ubuntu-apache
on main.tf line 13, in data "hcp_packer_iteration" "ubuntu-apache":
data "hcp_packer_iteration" "ubuntu-apache" {
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.

### Panic Output

https://gist.github.com/jpapazian2000/0052fd96b46333181b1af9fa5e929073

### Steps to Reproduce

 - create an ubuntu ami
 -  create an hcp packer bucket
 - create an iteration
 - use the above terraform code to provision the ami
I note that if I revoke the iteration, then I get the above crash in terraform, while I do not get the crash when the iteration is not present

### Expected Behavior

with the iteration revoked tfcb should have returned a message saying it can provision the ami as it is revoked

### Actual Behavior

crash

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### LINKED ISSUE #526: bug: revoked iterations causes panic
### Terraform Version and Provider Version

```
$ terraform -v
Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.2.0
+ provider registry.terraform.io/hashicorp/hcp v0.60.0
```

### Affected Resource(s)

* `hcp_packer_image` data source

### Terraform Configuration Files

```hcl
provider "hcp" {}

provider "aws" {
  region = "us-east-1"
}

data "hcp_packer_image" "learn-packer-amazonlinux2" {
  bucket_name    = "learn-packer-amazonlinux2-child"
  channel        = "latest"
  cloud_provider = "aws"
  region         = "us-east-1"
}

output "hcp_packer_image" {
  value = data.hcp_packer_image.learn-packer-amazonlinux2
}
```

### Debug Output

[gist: terraform-hcp-packer-panic.txt](https://gist.githubusercontent.com/lrstanley/47e2fee0472c256128d6afbefcb63366/raw/fa8b9c5c80c67c8f7c8e9a7576dfd2cbc282e8d2/terraform-hcp-packer-panic.txt)

### Panic Output

```
data.hcp_packer_image.learn-packer-amazonlinux2: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│   with data.hcp_packer_image.learn-packer-amazonlinux2,
│   on main.tf line 7, in data "hcp_packer_image" "learn-packer-amazonlinux2":
│    7: data "hcp_packer_image" "learn-packer-amazonlinux2" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-hcp_v0.60.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xdec396]

goroutine 99 [running]:
github.com/hashicorp/terraform-provider-hcp/internal/provider.dataSourcePackerImageRead({0x1207608, 0xc000136b40}, 0x0?, {0xf06480?, 0xc0005a21a0})
        github.com/hashicorp/terraform-provider-hcp/internal/provider/data_source_packer_image.go:171 +0x5d6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000267c00, {0x1207640, 0xc0005171d0}, 0xd?, {0xf06480, 0xc0005a21a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000267c00, {0x1207640, 0xc0005171d0}, 0xc0005e9d00, {0xf06480, 0xc0005a21a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000280db0, {0x1207640?, 0xc0005170b0?}, 0xc00028aa40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1195 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000599f40, {0x1207640?, 0xc000516720?}, 0xc0005c9090)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:658 +0x3ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x1031540?, 0xc000599f40}, {0x1207640, 0xc000516720}, 0xc0001e68c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x120a5e0, 0xc0005829c0}, 0xc000026d80, 0xc0005956e0, 0x19b2610, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x120a5e0, 0xc0005829c0}, 0xc000026d80, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-hcp_v0.60.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. Create two versions of an image in HCP Packer. Revoke both of them.
2. Reference the bucket name that contains both revoked iterations.
3. `terraform plan`

### Expected Behavior

Would expect the plan to work as expected (as nothing is actually preventing a revoked iteration from being used).

### Actual Behavior

Panics.

### Important Factoids

If I un-revoke one of the iterations, it works without issue, which makes me believe it is directly related. See also:

image

### References

* May be related: https://github.com/hashicorp/terraform-provider-hcp/issues/496
* May be related: https://github.com/hashicorp/terraform-provider-hcp/issues/493

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by aidan-mundy**
### :hammer_and_wrench: Description

Fixes #526 
Fixes #496 

- Fixes a bug where the image data source crashes when the channel it points to doesn't have an iteration assigned
- Adds a unit test for an empty channel 

### :building_construction: Acceptance tests

- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAcc.*PackerImage.* -test.v'
==> Checking that code complies with gofmt requirements...
golangci-lint run --config ./golangci-config.yml 
TF_ACC=1 go test ./internal/... -v -run=TestAcc.*PackerImage.* -test.v -timeout 360m -parallel=10
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/clients    0.468s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul     0.934s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/input      (cached) [no tests to run]
=== RUN   TestAcc_dataSourcePackerImage
--- PASS: TestAcc_dataSourcePackerImage (9.02s)
=== RUN   TestAcc_dataSourcePackerImage_revokedIteration
--- PASS: TestAcc_dataSourcePackerImage_revokedIteration (5.72s)
=== RUN   TestAcc_dataSourcePackerImage_emptyChannel
--- PASS: TestAcc_dataSourcePackerImage_emptyChannel (1.43s)
=== RUN   TestAcc_dataSourcePackerImage_channelAndIterationIDReject
--- PASS: TestAcc_dataSourcePackerImage_channelAndIterationIDReject (3.90s)
=== RUN   TestAcc_dataSourcePackerImage_channelAccept
--- PASS: TestAcc_dataSourcePackerImage_channelAccept (6.04s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider   26.774s
```

### CODE REVIEW

File: internal/provider/data_source_packer_image.go [hunk 1]
```diff
@@ -150,23 +151,18 @@ func dataSourcePackerImageRead(ctx context.Context, d *schema.ResourceData, meta
...
+		channel, err := clients.GetPackerChannelBySlug(
 			ctx,
 			client,
 			loc,
 			bucketName,
 			channelSlug)
 		if err != nil {
 			return diag.FromErr(err)
+		} else if channel.Iteration == nil {
+			return diag.Errorf("Channel does not have an assigned iteration (channel: %s)", channelSlug)
```
Comment (nywilken) [inline internal/provider/data_source_packer_image.go:164]: nit: I think this if check can stand on its own without the else statement. 
```suggestion
		} 
		if channel.Iteration == nil {
			return diag.Errorf("Channel does not have an assigned iteration (channel: %s)", channelSlug)
```

**Review by nywilken — APPROVED** [review]
This looks good to me. I left a nit but nothing worth blocking a merge.
